tbpprojekt/main/urls.py
#dio koda preuzet sa https://youtu.be/WuyKxdLcw3w

from django.urls import path
from . import views
from django.contrib.auth.decorators import user_passes_test
from .views import UserGroupsView

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('home', views.home, name='home'),
    path('sign-up', views.sign_up, name='sign_up'),
    path('create-post', views.create_post, name='create_post'),
    path('admin_stats', views.admin_stats, name='admin_stats'),
    path('admin_stats/user/<str:username>/', views.admin_user_actions, name='admin_user_actions'),
    path('user_groups/', user_passes_test(lambda u: u.is_staff)(UserGroupsView.as_view()), name='user_groups'),
]

tbpprojekt/tbpprojekt/urls.py
from django.contrib import admin
from django.urls import path, include 

urlpatterns = [
    path('admin/', admin.site.urls),
    path ('', include('main.urls')),
    path ('', include('django.contrib.auth.urls')),
]

tbpprojekt/ea/django/contrib/gis/db/backends/base/models.py
from django.contrib.gis import gdal


class SpatialRefSysMixin:
    """
    The SpatialRefSysMixin is a class used by the database-dependent
    SpatialRefSys objects to reduce redundant code.
    """

    @property
    def srs(self):
        """
        Return a GDAL SpatialReference object.
        """
        # TODO: Is caching really necessary here?  Is complexity worth it?
        if hasattr(self, "_srs"):
            # Returning a clone of the cached SpatialReference object.
            return self._srs.clone()
        else:
            # Attempting to cache a SpatialReference object.

            # Trying to get from WKT first.
            try:
                self._srs = gdal.SpatialReference(self.wkt)
                return self.srs
            except Exception as e:
                msg = e

            try:
                self._srs = gdal.SpatialReference(self.proj4text)
                return self.srs
            except Exception as e:
                msg = e

            raise Exception(
                "Could not get OSR SpatialReference from WKT: %s\nError:\n%s"
                % (self.wkt, msg)
            )

    @property
    def ellipsoid(self):
        """
        Return a tuple of the ellipsoid parameters:
        (semimajor axis, semiminor axis, and inverse flattening).
        """
        return self.srs.ellipsoid

    @property
    def name(self):
        "Return the projection name."
        return self.srs.name

    @property
    def spheroid(self):
        "Return the spheroid name for this spatial reference."
        return self.srs["spheroid"]

    @property
    def datum(self):
        "Return the datum for this spatial reference."
        return self.srs["datum"]

    @property
    def projected(self):
        "Is this Spatial Reference projected?"
        return self.srs.projected

    @property
    def local(self):
        "Is this Spatial Reference local?"
        return self.srs.local

    @property
    def geographic(self):
        "Is this Spatial Reference geographic?"
        return self.srs.geographic

    @property
    def linear_name(self):
        "Return the linear units name."
        return self.srs.linear_name

    @property
    def linear_units(self):
        "Return the linear units."
        return self.srs.linear_units

    @property
    def angular_name(self):
        "Return the name of the angular units."
        return self.srs.angular_name

    @property
    def angular_units(self):
        "Return the angular units."
        return self.srs.angular_units

    @property
    def units(self):
        "Return a tuple of the units and the name."
        if self.projected or self.local:
            return (self.linear_units, self.linear_name)
        elif self.geographic:
            return (self.angular_units, self.angular_name)
        else:
            return (None, None)

    @classmethod
    def get_units(cls, wkt):
        """
        Return a tuple of (unit_value, unit_name) for the given WKT without
        using any of the database fields.
        """
        return gdal.SpatialReference(wkt).units

    @classmethod
    def get_spheroid(cls, wkt, string=True):
        """
        Class method used by GeometryField on initialization to
        retrieve the `SPHEROID[..]` parameters from the given WKT.
        """
        srs = gdal.SpatialReference(wkt)
        sphere_params = srs.ellipsoid
        sphere_name = srs["spheroid"]

        if not string:
            return sphere_name, sphere_params
        else:
            # `string` parameter used to place in format acceptable by PostGIS
            if len(sphere_params) == 3:
                radius, flattening = sphere_params[0], sphere_params[2]
            else:
                radius, flattening = sphere_params
            return 'SPHEROID["%s",%s,%s]' % (sphere_name, radius, flattening)

    def __str__(self):
        """
        Return the string representation, a 'pretty' OGC WKT.
        """
        return str(self.srs)

tbpprojekt/main/models.py
#dio koda preuzet sa https://youtu.be/WuyKxdLcw3w

from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model
from django import forms

# Create your models here.

class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title + "\n" + self.description

class UserAction(models.Model):
    ACTION_TYPES = (
        ('POST', 'User created a post'),
        ('DELETE', 'User deleted a post by user'),
        ('BANNED', 'User banned user'),
        ('UNBANNED', 'User unbanned user'),
    )

    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='actions')
    action_type = models.CharField(max_length=12, choices=ACTION_TYPES)
    target_user = models.ForeignKey(get_user_model(), on_delete=models.SET_NULL, null=True, blank=True, related_name='targeted_actions')
    target_post = models.ForeignKey('Post', on_delete=models.SET_NULL, null=True, blank=True)
    deleted_post_author = models.CharField(max_length=150, null=True, blank=True)  # novo polje za spremanje imena autora izbrisanog posta
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        if self.action_type == 'POST':
            return f"User {self.user.username} created a post at {self.timestamp}"
        elif self.action_type == 'DELETE':
            return f"User {self.user.username} deleted a post by {self.deleted_post_author} at {self.timestamp}"  # koristimo deleted_post_author umjesto self.target_post.author.username
        elif self.action_type == 'BANNED':
            return f"User {self.user.username} banned user {self.target_user.username} at {self.timestamp}"
        elif self.action_type == 'UNBANNED':
            return f"User {self.user.username} unbanned user {self.target_user.username} at {self.timestamp}"

tbpprojekt/main/forms.py
#dio koda preuzet sa https://youtu.be/WuyKxdLcw3w

from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User, Group
from .models import Post

class RegisterForm(UserCreationForm):
    email = forms.EmailField(required=True)
    first_name = forms.CharField(required=False)
    last_name = forms.CharField(required=False)
    class Meta:
        model = User
        fields = ["username", "email", "first_name", "last_name", "password1", "password2"]

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ["title", "description"]

class CreateGroupForm(forms.Form):
    group_name = forms.CharField(max_length=80)

class DeleteGroupForm(forms.Form):
    group = forms.ModelChoiceField(queryset=Group.objects.all())

class AddRemoveUserForm(forms.Form):
    add_user = forms.ModelChoiceField(queryset=User.objects.all(), required=False)
    #remove_user = forms.ModelChoiceField(queryset=User.objects.all(), required=False)
    group = forms.ModelChoiceField(queryset=Group.objects.all())

tbpprojekt/main/views.py
#dio koda preuzet sa https://youtu.be/WuyKxdLcw3w

from django.shortcuts import render, redirect
from .forms import RegisterForm, PostForm, CreateGroupForm, DeleteGroupForm, AddRemoveUserForm
from django.contrib.auth.decorators import login_required, permission_required, user_passes_test
from django.contrib.auth import login, logout, authenticate, get_user_model
from django.contrib.auth.models import User, Group
from django.shortcuts import render, get_object_or_404
from .models import UserAction, Post
from django.db.models import Count, Avg
from django.views import View
from django.contrib import messages

# Create your views here.

@user_passes_test(lambda u: u.is_staff)
def admin_stats(request):
    user_count = User.objects.count()
    post_count = Post.objects.count()
    if user_count > 0:  #ne dijeli s nulom
        avg_posts_per_user = post_count / user_count
    else:
        avg_posts_per_user = 0
    avg_posts_per_user = round(avg_posts_per_user, 2)
    # User activity information
    users = User.objects.annotate(num_posts=Count('post')).all()
    # Post statistics
    posts = Post.objects.all()
    # Group statistics
    groups = Group.objects.annotate(num_users=Count('user')).all()
    return render(request, 'main/admin_stats.html', {
        'user_count': user_count,
        'post_count': post_count,
        'avg_posts_per_user': avg_posts_per_user,
        'users': users,
        'posts': posts,
        'groups': groups,
    })

@user_passes_test(lambda u: u.is_staff)
def admin_user_actions(request, username):
    user = get_object_or_404(get_user_model(), username=username)
    actions = UserAction.objects.filter(user=user).order_by('-timestamp')
    return render(request, 'main/admin_user_actions.html', {'actions': actions, 'username': username})


@login_required(login_url="/login")
@permission_required("main.add_post", login_url="/login", raise_exception=True)
def create_post(request):
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            UserAction.objects.create(user=request.user, action_type='POST')
            return redirect("/home")
    else:
        form = PostForm()
    return render(request, 'main/create_post.html', {"form": form})

@login_required(login_url="/login")
def home(request):
    posts = Post.objects.all()
    banned_users = User.objects.filter(groups__name__in=['Banned', 'Bannedmoderator'])
    if request.method == "POST":
        post_id = request.POST.get("post-id")
        ban_user_id = request.POST.get("ban-user-id")
        unban_user_id = request.POST.get("unban-user-id")
        if post_id:
            post = Post.objects.filter(id=post_id).first()
            if post and (post.author == request.user or request.user.has_perm("main.delete_post")):
                if post and (post.author == request.user or request.user.has_perm("main.delete_post")):
                    #UserAction.objects.create(user=request.user, action_type='DELETE', target_post=post, deleted_post_author=post.author.username)
                    #UserAction.objects.create(user=request.user, action_type='DELETE', target_post=post)
                    UserAction.objects.create(user=request.user, action_type='DELETE', target_user=post.author)
                    post.delete()
        elif ban_user_id:
            user = User.objects.filter(id=ban_user_id).first()
            if user and request.user.is_staff:
                if user.groups.filter(name='Moderator').exists():
                    try:
                        group = Group.objects.get(name='Moderator')
                        group.user_set.remove(user)
                        group = Group.objects.get(name='Bannedmoderator')
                        group.user_set.add(user)
                        UserAction.objects.create(user=request.user, action_type='BANNED', target_user=user)
                    except:
                        pass
                else:
                    try:
                        group = Group.objects.get(name=user.groups.first().name)
                        group.user_set.remove(user)
                        group = Group.objects.get(name='Banned')
                        group.user_set.add(user)
                        UserAction.objects.create(user=request.user, action_type='BANNED', target_user=user)
                    except:
                        pass
        elif unban_user_id:
            user = User.objects.filter(id=unban_user_id).first()
            if user and request.user.is_staff:
                if user.groups.filter(name='Banned').exists():
                    try:
                        group = Group.objects.get(name='Banned') 
                        group.user_set.remove(user)
                        group = Group.objects.get(name='Registrirani')
                        group.user_set.add(user)
                        UserAction.objects.create(user=request.user, action_type='UNBANNED', target_user=user)
                    except:
                        pass
                elif user.groups.filter(name='Bannedmoderator').exists():
                    try:
                        group = Group.objects.get(name='Bannedmoderator')
                        group.user_set.remove(user)
                        group = Group.objects.get(name='Moderator')
                        group.user_set.add(user)
                        UserAction.objects.create(user=request.user, action_type='UNBANNED', target_user=user)
                    except:
                        pass
    return render(request, 'main/home.html', {"posts": posts, "banned_users": banned_users})

def sign_up(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('/home')
    else:
        form = RegisterForm()
    return render(request, 'registration/sign_up.html', {"form": form})


class UserGroupsView(View):
    def get(self, request):
        groups = Group.objects.all()
        users = User.objects.all()
        create_group_form = CreateGroupForm()
        add_remove_user_form = AddRemoveUserForm()
        delete_group_form = DeleteGroupForm()
        return render(request, 'main/user_groups.html', {
            'groups': groups,
            'users': users,
            'create_group_form': create_group_form,
            'add_remove_user_form': add_remove_user_form,
            'delete_group_form': delete_group_form
        })
    def post(self, request):
        create_group_form = CreateGroupForm(request.POST)
        add_remove_user_form = AddRemoveUserForm(request.POST)
        #delete_group_form = DeleteGroupForm(request.POST)
        if create_group_form.is_valid():
            # Create new group
            group_name = create_group_form.cleaned_data.get('group_name')
            Group.objects.create(name=group_name)
        
        if add_remove_user_form.is_valid():
            # Add/remove users to/from group
            add_user = add_remove_user_form.cleaned_data.get('add_user')
            group_remove = add_user.groups.first() # get the first (and only) group of the user
            group_add = add_remove_user_form.cleaned_data.get('group')
            if add_user and group_add != group_remove: # check if user is already in the group
                group_add.user_set.add(add_user)
                if group_remove: # Check if there's a group to remove the user from
                    group_remove.user_set.remove(add_user)

        return redirect('main:user_groups')

tbpprojekt/main/templates/main/admin_stats.html
{% extends 'main/base.html' %}
{% block title %}Admin Stats{% endblock %}
{% block content %}
    <h2>Statistics</h2>
    <p>Total users: {{ user_count }}</p>
    <p>Total posts: {{ post_count }}</p>
    <p>Average posts per user: {{ avg_posts_per_user }}</p>

    <h3>General User Activity</h3>
    <ul>
        {% for user in users %}
            <li>{{ user.username }}: {{ user.num_posts }} posts, last login {{ user.last_login }}, account created {{ user.date_joined }}</li>
        {% endfor %}
    </ul>

    <h3>User Actions</h3>
    <ul>
        {% for user in users %}
            <li><a href="{% url 'main:admin_user_actions' user.username %}">{{ user.username }}</a></li>
        {% endfor %}
    </ul>

    <h3>Post Statistics</h3>
    <ul>
        {% for post in posts %}
            <li>{{ post.title }}: created {{ post.created_at }}, last updated {{ post.updated_at }}</li>
        {% endfor %}
    </ul>

    <h3>Group Statstics</h3>
    <ul>
        {% for group in groups %}
            <li>{{ group.name }}: {{ group.num_users }} users</li>
        {% endfor %}
    </ul>
{% endblock %}

tbpprojekt/main/templates/main/admin_user_actions.html
{% extends 'main/base.html' %}
{% block title %}User Actions{% endblock %}
{% block content %}
    <h2>User actions for {{ username }}</h2>
    <ul>
        {% for action in actions %}
        <li>
            {{ action.get_action_type_display }} 
            {% if action.target_user %}
                {{ action.target_user.username }}
            {% endif %}
            at {{ action.timestamp }}
        </li>
    {% endfor %}
    </ul>
{% endblock %}

tbpprojekt/main/templates/main/base.html
<!--dio koda preuzet sa https://youtu.be/WuyKxdLcw3w -->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous"
    />
    <title>{% block title %}TBP projekt - User management app{% endblock %}</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <div>
                <ul class="navbar-nav">
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="/home">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/create-post">Post</a>
                    </li>
                    {% endif %}
                    {% if user.is_staff %}
                    <li class="nav-item">
                        <a class="nav-link" href="/admin">Admin</a>
                    </li>
                    <li>
                        <a class="nav-link" href="/user_groups">User Groups</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/admin_stats">Admin Stats</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
            <div>
                <ul class="navbar-nav">
                    {% if user.is_authenticated %}
                    <span class="navbar-text">
                        Logged in as {{user.username}} |
                        {% if user.is_staff %}
                            Admin |
                        {% elif user.groups.exists %}
                            {% for group in user.groups.all %}
                                {{ group.name }} |
                            {% endfor %}
                        {% else %}
                            No group |
                        {% endif %}
                    </span>

                    <li class="nav-item">
                      <a class="nav-link" href="/logout">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                      <a class="nav-link" href="/login">Login</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
      crossorigin="anonymous"
    ></script>
</body>
</html>

tbpprojekt/main/templates/main/create_post.html
{% extends 'main/base.html' %} {% block title %}Create a Post{% endblock %} 
{% load crispy_forms_tags %} {% block content %}
<form method="post">
  {% csrf_token %}{{form|crispy}}
  <button type="submit" class="btn btn-success">Post</button>
</form>
{% endblock %}

tbpprojekt/main/templates/main/home.html
<!--dio koda preuzet sa https://youtu.be/WuyKxdLcw3w -->

{% extends 'main/base.html' %}
{% block title %}Home Page{% endblock %} 
{% block content %}
{% for post in posts %}
<div class="card mt-2">
  <div class="card-header"><strong>@{{ post.author.username }}</strong></div>
  <div class="card-body d-flex flex-row justify-content-between">
    <div>
      <h5 class="card-title">{{post.title}}</h5>
      <p>{{post.description}}</p>
    </div>
    <div>
      {% if user == post.author or perms.main.delete_post %}
      <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger mr-2" style="width: 150px;" name="post-id" value="{{post.id}}">Delete</button>
      </form>
      {% endif %}

      {% if user.is_staff and not post.author.is_staff %}
      <form method="post">
        {% csrf_token %}
        {% if post.author in banned_users %}
        <button type="submit" class="btn btn-primary mr-2" style="width: 150px;" name="unban-user-id" value="{{post.author.id}}">Unban User</button>
        {% else %}
        <button type="submit" class="btn btn-warning mr-2" style="width: 150px;" name="ban-user-id" value="{{post.author.id}}">Ban User</button>
        {% endif %}
      </form>
      {% endif %}
      
    </div>
  </div>
  <div class="card-footer text-muted">{{post.created_at}}</div>
</div>
{% empty %}
<p>No posts yet</p>
{% endfor %} {% endblock %}

tbpprojekt/main/templates/main/user_groups.html
<style>
    table {
        border-collapse: collapse;
        width: 100%;
    }

    th, td {
        border: 1px solid #ddd;
        padding: 8px;
        text-align: left;
    }

    tr:nth-child(even) {
        background-color: #f2f2f2;
    }

    th {
        background-color: #4CAF50;
        color: white;
    }
</style>

{% extends 'main/base.html' %}
{% block content %}

    <form method="post">
        {% csrf_token %}
        <h3>Create new group</h3>
        {{ create_group_form.as_p }}
        <button type="submit">Create Group</button>
    </form> 

<!--
    <form method="post">
        {% csrf_token %}
        {{ delete_group_form }}
        <input type="submit" value="Delete Group">
    </form>   
--> 

    <form method="post">
        {% csrf_token %}
        <h3>Add user to group</h3>
        {{ add_remove_user_form.as_p }}
        <button type="submit">Submit</button>
    </form>

    <h3>Existing Groups</h3>
    <table>
        <tr>
            <th>Group</th>
            <th>Members</th>
        </tr>
        {% for group in groups %}
            <tr>
                <td>{{ group.name }}</td>
                <td>
                    <ul>
                        {% for user in group.user_set.all %}
                            <li>{{ user.username }}</li>
                        {% endfor %}
                    </ul>
                </td>
            </tr>
        {% endfor %}
        <tr>
            <td>Admin</td>
            <td>
                <ul>
                    {% for user in users %}
                        {% if user.is_staff %}
                            <li>{{ user.username }}</li>
                        {% endif %}
                    {% endfor %}
                </ul>
            </td>
        </tr>
    </table>    

{% endblock %}